# Generated by Django 4.2.7 on 2026-04-06 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('sessions', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'url_analysis_data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='URLPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('url_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_data', to='api.urlanalysisdata')),
            ],
            options={
                'db_table': 'url_page_data',
                'ordering': ['-views'],
                'indexes': [models.Index(fields=['url_analysis', '-views'], name='url_page_da_url_ana_e93e16_idx')],
            },
        ),
        migrations.CreateModel(
            name='URLKeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('url_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_data', to='api.urlanalysisdata')),
            ],
            options={
                'db_table': 'url_keyword_data',
                'ordering': ['-clicks'],
                'indexes': [models.Index(fields=['url_analysis', '-clicks'], name='url_keyword_url_ana_7d7345_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='urlanalysisdata',
            index=models.Index(fields=['user', 'url', '-date'], name='url_analysi_user_id_a72f97_idx'),
        ),
        migrations.AddIndex(
            model_name='urlanalysisdata',
            index=models.Index(fields=['url', '-date'], name='url_analysi_url_a2b072_idx'),
        ),
    ]
