# Generated by Django 4.2.7 on 2026-04-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_urlanalysisdata_urlpagedata_urlkeyworddata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('semantic_score', models.PositiveIntegerField(default=0)),
                ('technical_score', models.PositiveIntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('technical_issues', models.JSONField(blank=True, default=dict)),
                ('competitor_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.AddIndex(
            model_name='contentanalysis',
            index=models.Index(fields=['user', '-last_updated'], name='api_content_user_id_b2bb67_idx'),
        ),
        migrations.AddIndex(
            model_name='contentanalysis',
            index=models.Index(fields=['url'], name='api_content_url_8c1a0b_idx'),
        ),
    ]
