# Generated by Django 4.2.7 on 2026-04-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contentanalysis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentanalysis',
            new_name='api_content_user_id_c91f83_idx',
            old_name='api_content_user_id_b2bb67_idx',
        ),
        migrations.RenameIndex(
            model_name='contentanalysis',
            new_name='api_content_url_a0f753_idx',
            old_name='api_content_url_8c1a0b_idx',
        ),
    ]
