databases:
  - name: mon-projet-db
    databaseName: mon_projet
    user: mon_projet_user

services:
  - type: web
    name: mon-projet-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mon-projet-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_USE_DOTENV
        value: "False"
      - key: ENABLE_CREATE_ADMIN_PAGE
        value: "False"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: mon-projet-ve8t.onrender.com,mon-projet-backend.onrender.com,.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://hassen100.github.io,https://hassen100.github.io/mon-projet
      - key: CSRF_TRUSTED_ORIGINS
        value: https://mon-projet-ve8t.onrender.com,https://mon-projet-backend.onrender.com,https://hassen100.github.io,https://hassen100.github.io/mon-projet
